<?php

/**
 * @file
 * The farmOS UI Views module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;

/**
 * Implements hook_farm_dashboard_panes().
 */
function farm_ui_views_farm_dashboard_panes() {
  $panes = [];

  // If the plan module is enabled, add active plans pane.
  if (\Drupal::service('module_handler')->moduleExists('plan')) {
    $panes['active_plans'] = [
      'view' => 'farm_plan',
      'view_display_id' => 'block_active',
      'group' => 'plans',
      'weight' => 0,
    ];
  }

  // Add upcoming and late logs panes.
  $panes['upcoming_tasks'] = [
    'view' => 'farm_log',
    'view_display_id' => 'block_upcoming',
    'group' => 'logs',
    'weight' => 10,
  ];
  $panes['late_tasks'] = [
    'view' => 'farm_log',
    'view_display_id' => 'block_late',
    'group' => 'logs',
    'weight' => 11,
  ];

  return $panes;
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function farm_ui_views_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {

  // Use Entity Browser widget for certain asset reference fields.
  $alter_fields = [
    'log' => [
      'asset',
    ],
    'quantity' => [
      'inventory_asset',
    ],
  ];
  foreach ($alter_fields as $entity_type_id => $field_names) {
    if ($entity_type->id() != $entity_type_id) {
      continue;
    }
    foreach ($field_names as $field_name) {
      if (!empty($fields[$field_name])) {
        /** @var \Drupal\Core\Field\BaseFieldDefinition[] $fields */
        $form_display_options = $fields[$field_name]->getDisplayOptions('form');
        $form_display_options['type'] = 'entity_browser_entity_reference';
        $form_display_options['settings'] = [
          'entity_browser' => 'farm_asset',
          'field_widget_display' => 'label',
          'field_widget_remove' => TRUE,
          'open' => TRUE,
          'selection_mode' => 'selection_append',
          'field_widget_edit' => FALSE,
          'field_widget_replace' => FALSE,
          'field_widget_display_settings' => [],
        ];
        $fields[$field_name]->setDisplayOptions('form', $form_display_options);
      }
    }
  }
}

/**
 * Implements hook_views_pre_view().
 */
function farm_ui_views_views_pre_view(ViewExecutable $view, $display_id, array &$args) {

  // We only want to alter the Views we provide.
  if (!in_array($view->id(), ['farm_asset', 'farm_log', 'farm_plan', 'farm_quantity'])) {
    return;
  }

  // Only alter the "By type" display if a type is provided.
  if ($display_id == 'page_type' && !empty($args[0])) {

    // Remove the type field and filter handlers.
    $view->removeHandler($display_id, 'field', 'type');
    $view->removeHandler($display_id, 'filter', 'type');

    // Get the entity and bundle.
    $base_entity = $view->getBaseEntityType();
    $bundle = $args[0];

    /** @var \Drupal\Core\Entity\EntityTypeManagerInterface $entity_type_manager */
    $entity_type_manager = \Drupal::entityTypeManager();

    // If the entity type has a bundle_plugin manager, add all of its
    // bundle fields and filters to the page_type view.
    if ($entity_type_manager->hasHandler($base_entity->id(), 'bundle_plugin')) {

      /** @var \Drupal\Core\Entity\Sql\DefaultTableMapping $table_mapping */
      $table_mapping = \Drupal::entityTypeManager()->getStorage($base_entity->id())->getTableMapping();

      // Load bundle fields.
      $bundle_fields = $entity_type_manager->getHandler($base_entity->id(), 'bundle_plugin')->getFieldDefinitions($bundle);
      foreach ($bundle_fields as $field_name => $field_definition) {

        // Get the field's table column (main property name).
        $table = $table_mapping->getFieldTableName($field_name);
        $property_name = $field_definition->getFieldStorageDefinition()->getMainPropertyName();

        // Build the column and table names.
        $column_name = $field_name . '_' . $property_name;
        $views_option_name = $table . '.' . $column_name;

        // Add a field handler if a views data field definition exists.
        $field_options = Views::viewsDataHelper()->fetchFields($table, 'field');
        if (isset($field_options[$views_option_name])) {
          // Add bundle fields to the view.
          $view->addHandler('page_type', 'field', $table, $column_name);
        }

        // Add a filter handler if a views data filter definition exists.
        $filter_options = Views::viewsDataHelper()->fetchFields($table, 'filter');
        if (isset($filter_options[$views_option_name])) {
          // Add bundle filters to the view.
          $filter = [
            'id' => $column_name,
            'table' => $table,
            'field' => $column_name,
            'exposed' => TRUE,
            'expose' => [
              'operator_id' => $column_name . '_op',
              'label' => $filter_options[$views_option_name]['title'],
              'identifier' => $column_name,
              'multiple' => TRUE,
            ],
            'entity_type' => $base_entity,
            'entity_field' => $column_name,
          ];
          $view->addHandler('page_type', 'filter', $table, $column_name, $filter);
        }
      }
    }
  }

  // If this is the "Upcoming" or "Late" Logs block display, add a "more" link
  // that points to the default page display with appropriate filters.
  if ($view->id() == 'farm_log' && in_array($display_id, ['block_upcoming', 'block_late'])) {
    $view->display_handler->setOption('use_more', TRUE);
    $view->display_handler->setOption('use_more_always', TRUE);
    $view->display_handler->setOption('link_display', 'custom_url');
    $today = date('Y-m-d', \Drupal::time()->getRequestTime());
    if ($display_id == 'block_upcoming') {
      $view->display_handler->setOption('use_more_text', t('View all upcoming logs'));
      $view->display_handler->setOption('link_url', 'logs?status[]=pending&start=' . $today);
    }
    elseif ($display_id == 'block_late') {
      $view->display_handler->setOption('use_more_text', t('View all late logs'));
      $view->display_handler->setOption('link_url', 'logs?status[]=pending&end=' . $today);
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function farm_ui_views_views_pre_render(ViewExecutable $view) {

  // We only want to alter the Views we provide.
  if (!in_array($view->id(), ['farm_asset', 'farm_log', 'farm_plan', 'farm_quantity'])) {
    return;
  }

  // Get all asset bundles.
  $asset_bundles = \Drupal::service('entity_type.bundle.info')->getBundleInfo($view->getBaseEntityType()->id());

  // If this is the "By type" display and a bundle argument is specified, load
  // the bundle label and set the title.
  if ($view->current_display == 'page_type' && !empty($view->args[0])) {
    $bundle = $view->args[0];
    if (!empty($asset_bundles[$bundle])) {
      $view->setTitle($asset_bundles[$bundle]['label'] . ' ' . $view->getBaseEntityType()->getPluralLabel());
    }
  }

  // Render a map attachment above views of assets.
  if ($view->id() == 'farm_asset' && in_array($view->current_display, ['page', 'page_type'])) {

    // Get exposed filters.
    $exposed_filters = $view->getExposedInput();

    // Start array of filtered bundles.
    $filtered_bundles = $asset_bundles;

    // Start array of asset layers to add.
    $asset_layers = [];

    // Add multiple asset layers to the page of all assets.
    if ($view->current_display == 'page') {

      // Limit to filtered asset types.
      if (!empty($exposed_filters['type'])) {
        $filtered_bundles = array_intersect_key($asset_bundles, array_flip($exposed_filters['type']));
      }
    }

    // If this is the page_type display, only map this asset type.
    if ($view->current_display == 'page_type' && !empty($view->args[0])) {
      $bundle = $view->args[0];
      $filtered_bundles = [
        $bundle => $asset_bundles[$bundle],
      ];
    }

    // Save the translated assets label.
    $assets_label = $view->getBaseEntityType()->getCollectionLabel();

    // Add an asset type map layer for each filtered bundle.
    foreach ($filtered_bundles as $bundle => $bundle_info) {

      // The default layer group should be "Assets".
      $layer_group = $assets_label;

      // Create individual layers for land types and structure types.
      // @todo Abstract this to detect types other than land/structure?
      if (in_array($bundle, ['land', 'structure'])) {

        // Get fields for the bundle.
        $entity_manager = \Drupal::service('entity_field.manager');
        $fields = $entity_manager->getFieldStorageDefinitions('asset', $bundle);
        $type_field_name = $bundle . '_type';

        // Create a group for the asset bundle.
        $bundle_group = t('@bundle assets', ['@bundle' => $bundle_info['label']]);

        // Get valid options for the bundle_type field.
        $options = options_allowed_values($fields[$type_field_name]);
        foreach ($options as $option => $label) {

          // Add an exposed filter for the bundle_type field.
          $exposed_filters[$type_field_name . '[]'] = $option;

          // Add layer for the bundle type.
          $asset_layers[$bundle . '_' . $option] = [
            'group' => $bundle_group,
            'label' => $label,
            'asset_type' => $bundle,
            'filters' => $exposed_filters,
            // @todo Color each asset type differently.
            // This was previously provided with hook_farm_area_type_info.
            'color' => 'orange',
            'zoom' => TRUE,
          ];
        }

        continue;
      }

      // Add an asset layer.
      $asset_layers[$bundle] = [
        'group' => $layer_group,
        'label' => $bundle_info['label'],
        'asset_type' => $bundle,
        'filters' => $exposed_filters,
        // @todo Color each asset type differently.
        // This was previously provided with hook_farm_area_type_info.
        'color' => 'orange',
        'zoom' => TRUE,
      ];
    }

    // Build the map render array.
    $map = [
      '#type' => 'farm_map',
      '#map_type' => 'asset_list',
    ];
    $map['#map_settings']['asset_type_layers'] = $asset_layers;

    // Render the map.
    $view->attachment_before['asset_map'] = $map;
  }
}
