<?php
/**
 * @file
 * Code for the Farm Quick module.
 */

/**
 * Load information about all quick forms provided by other modules.
 */
function farm_quick_forms() {

  // Ask modules for quick forms.
  $forms = module_invoke_all('farm_quick_forms');

  // Sort the quick forms.
  uasort($forms, 'farm_quick_forms_sort');

  // Return the array of quick forms.
  return $forms;
}

/**
 * Sort function for quick form definitions.
 */
function farm_quick_forms_sort($a, $b) {

  // Sort alphabetically by the 'tab' property.
  return strcasecmp($a['tab'], $b['tab']);
}

/**
 * Implements hook_menu().
 */
function farm_quick_menu() {

  // Start with an empty menu items array.
  $items = array();

  // Ask for quick forms from modules.
  $forms = farm_quick_forms();

  // If there are no forms, bail.
  if (empty($forms)) {
    return $items;
  }

  // Add a menu item for each form.
  reset($forms);
  $first = key($forms);
  foreach ($forms as $name => $form) {

    // Build a menu item definition.
    $menu_item = array(
      'title' => $form['tab'],
      'page callback' => 'drupal_get_form',
      'page arguments' => array($form['form']),
      'access arguments' => array($form['permission']),
      'type' => MENU_LOCAL_TASK,
    );

    // If this is the first item, make it the default tab for "Quick forms".
    if ($name == $first) {
      $items['farm/quick'] = $menu_item;
      $items['farm/quick']['title'] = 'Quick forms';
      $items['farm/quick']['type'] = MENU_LOCAL_TASK;
      $items['farm/quick/' . $name] = array(
        'title' => $menu_item['title'],
        'type' => MENU_DEFAULT_LOCAL_TASK,
      );
    }

    // Otherwise, treat it as a normal menu tab.
    else {
      $items['farm/quick/' . $name] = $menu_item;
    }
  }

  // Return menu items.
  return $items;
}
