<?php

/**
 * @file
 * The farm_map module.
 */

/**
 * Implements hook_theme().
 */
function farm_map_theme($existing, $type, $theme, $path) {
  return [
    'farm_map' => [
      'variables' => [
        'attributes' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_farm_dashboard_panes().
 */
function farm_map_farm_dashboard_panes() {
  return [
    'dashboard_map' => [
      'block' => 'dashboard_map',
    ],
  ];
}
