<?php
/**
 * @file
 * Code for the Farm Water Test feature.
 */

include_once 'farm_water_test.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_water_test_farm_ui_entities() {
  return array(
    'log' => array(
      'farm_water_test' => array(
        'label' => t('Water test'),
        'label_plural' => t('Water test'),
        'view' => 'farm_water_test',
        'farm_asset' => 'none',
        'areas' => TRUE,
      ),
    ),
  );
}

/**
 * Implements hook_farm_taxonomy_term_view_views().
 */
function farm_water_test_farm_taxonomy_term_view_views($term) {

  // If the term is not an area, bail.
  if ($term->vocabulary_machine_name != 'farm_areas') {
    return array();
  }

  // Return a list of Views to include on Areas.
  return array(
    'farm_water_test',
  );
}
