<?php
/**
 * @file
 * Code for the Farm Water Test feature.
 */

include_once 'farm_water_test.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_water_test_farm_ui_entities() {
  return array(
    'log' => array(
      'farm_water_test' => array(
        'label' => t('Water test'),
        'label_plural' => t('Water test'),
        'view' => 'farm_water_test',
        'farm_asset' => 'none',
      ),
    ),
  );
}

/**
 * Implements hook_farm_ui_actions().
 */
function farm_water_test_farm_ui_actions() {

  // Define farm area actions.
  $actions = array(
    'water_test' => array(
      'title' => t('Add a water test'),
      'href' => 'log/add/farm_water_test',
      'paths' => array(
        'taxonomy/term/%',
      ),
    ),
  );
  return $actions;
}

/**
 * Implements hook_farm_taxonomy_term_view_views().
 */
function farm_water_test_farm_taxonomy_term_view_views($term) {

  // If the term is not an area, bail.
  if ($term->vocabulary_machine_name != 'farm_areas') {
    return array();
  }

  // Return a list of Views to include on Areas.
  return array(
    'farm_water_test',
  );
}

/**
 * Implements hook_farm_area_links().
 */
function farm_water_test_farm_area_links($id) {
  $links = array();

  // Add link to water tests.
  $view = views_get_view('farm_water_test');
  $view->preview('default', array($id));
  if ($view->total_rows > 0) {
    $links[] = array(
      'title' => t('Water tests') . ': ' . $view->total_rows,
      'href' => 'farm/logs/water-tests/' . $id,
    );
  }

  return $links;
}
