<?php

/**
 * @file
 * The farmOS Equipment module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function farm_equipment_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  // Add equipment reference field to logs.
  if ($entity_type->id() == 'log') {

    // Include helper functions.
    module_load_include('inc', 'farm_field', 'farm_field.base_fields');

    // Build field options.
    $options = [
      'type' => 'entity_reference',
      'label' => t('Equipment used'),
      'description' => t('What equipment was used?'),
      'target_type' => 'asset',
      'multiple' => TRUE,
      'weight' => [
        'form' => 55,
        'view' => -5,
      ],
    ];
    $field = \Drupal::service('farm_field.factory')->bundleFieldDefinition($options);
    $field->setSetting('handler', 'default:asset');
    $field->setSetting('handler_settings', [
      'target_bundles' => [
        'equipment' => 'equipment',
      ],
      'sort' => [
        'field' => '_none',
      ],
      'auto_create' => FALSE,
      'auto_create_bundle' => '',
    ]);
    $fields['equipment'] = $field;
  }

  return $fields;
}
