<?php

/**
 * @file
 * Contains farm_equipment.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function farm_equipment_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  // Add an Equipment reference field to logs.
  if ($entity_type->id() == 'log') {
    $options = [
      'type' => 'entity_reference',
      'label' => t('Equipment used'),
      'description' => t('What equipment was used?'),
      'target_type' => 'asset',
      'target_bundle' => 'equipment',
      'multiple' => TRUE,
      'weight' => [
        'form' => 55,
        'view' => -5,
      ],
    ];
    $fields['equipment'] = \Drupal::service('farm_field.factory')->baseFieldDefinition($options);
  }

  return $fields;
}
