<?php
/**
 * @file
 * Code for the Farm Log: Sale feature.
 */

include_once 'farm_log_sale.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_log_sale_farm_ui_entities() {
  return array(
    'log' => array(
      'farm_sale' => array(
        'label' => t('Sale'),
        'label_plural' => t('Sales'),
        'view' => 'farm_log_sale',
        'weight' => 90,
      ),
    ),
  );
}
