<?php
/**
 * @file
 * Code for the Farm Maps feature.
 */

include_once 'farm_map.features.inc';

/**
 * Implements hook_openlayers_object_preprocess_alter().
 */
function farm_map_openlayers_object_preprocess_alter(&$build, $context) {

  // If the object is a Map...
  if ($context instanceof Drupal\openlayers\Types\MapInterface) {

    // If the map machine name starts with "farm_", add farm map CSS.
    if (substr($context->getMachineName(), 0, 5) == 'farm_') {
      drupal_add_css(drupal_get_path('module', 'farm_map') . '/farm_map.css');
    }
  }
}
