<?php
/**
 * @file
 * Code for the Farm Equipment feature.
 */

include_once 'farm_equipment.features.inc';

function farm_equipment_farm_admin_actions() {

  // Define farm area actions.
  $actions = array(
    'equipment' => array(
      'title' => t('Add equipment'),
      'href' => 'farm/asset/add/equipment',
      'paths' => array(
        'farm/area/%/equipment',
        'farm/equipment',
        'farm/equipment/list',
      ),
    ),
    'maintenance' => array(
      'title' => t('Add maintenance'),
      'href' => 'log/add/farm_maintenance',
      'paths' => array(
        'farm/equipment',
        'farm/equipment/list',
        'farm/equipment/maintenance',
      ),
      'assets' => array(
        'equipment',
      ),
    ),
  );
  return $actions;
}

/**
 * Implements hook_form_alter().
 */
function farm_equipment_form_alter(&$form, &$form_state, $form_id) {

  // If this is a log form with a planting reference field...
  if ($form_id == 'log_form' && !empty($form['field_farm_equipment'])) {

    // Alter the form with the farm_log helper function.
    farm_log_form_prepopulate_asset($form, 'field_farm_equipment');
  }
}

/**
 * Implements hook_farm_area_links().
 */
function farm_equipment_farm_area_links($id) {
  return array(
    array(
      'title' => t('Equipment'),
      'href' => 'farm/area/' . $id . '/equipment',
    ),
  );
}
