<?php
/**
 * @file
 * Code for the Farm MapKnitter module.
 */

/**
 * Implements hook_permission().
 */
function farm_mapknitter_permission() {
  $perms = array(
    'administer farm_mapknitter module' => array(
      'title' => t('Administer farm MapKnitter module'),
    ),
  );
  return $perms;
}

/**
 * Implements hook_farm_manager_perms().
 */
function farm_mapknitter_farm_manager_perms() {

  // Give farm managers access to the mapknitter config.
  return array('administer farm_mapknitter module');
}

/**
 * Implements hook_menu().
 */
function farm_mapknitter_menu() {
  $items = array();

  $items['admin/config/farm/mapknitter'] = array(
    'title' => 'MapKnitter Layers',
    'description' => 'Include MapKnitter layers in your farm maps.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('farm_mapknitter_form'),
    'access arguments' => array('administer farm_mapknitter module'),
  );

  return $items;
}

/**
 * MapKnitter configuration form.
 */
function farm_mapknitter_form($form, &$form_state) {

  $form['farm_mapknitter_title'] = array(
    '#type' => 'textfield',
    '#title' => t('MapKnitter TMS Title'),
    '#description' => t('Give the MapKnitter TMS layer a name.'),
    '#default_value' => variable_get('farm_mapknitter_title', ''),
  );

  $form['farm_mapknitter_url'] = array(
    '#type' => 'textfield',
    '#title' => t('MapKnitter TMS URL'),
    '#description' => t('Enter the URL of the MapKnitter TMS layer you would like to include in your map.'),
    '#default_value' => variable_get('farm_mapknitter_url', ''),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_ctools_plugin_api().
 */
function farm_mapknitter_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "openlayers" && $api == "default_openlayers_layers") {
    return array("version" => "1");
  }
  if ($module == "openlayers" && $api == "default_openlayers_maps") {
    return array("version" => "1");
  }
  if ($module == "openlayers" && $api == "default_openlayers_sources") {
    return array("version" => "1");
  }
}
