<?php
/**
 * @file
 * Code for the Farm Livestock feature.
 */

include_once 'farm_livestock.features.inc';

/**
 * Implements hook_farm_admin_actions().
 */
function farm_livestock_farm_admin_actions() {

  // Define farm area actions.
  $actions = array(
    'animal' => array(
      'title' => t('Add an animal'),
      'href' => 'farm/asset/add/animal',
      'views' => array(
        'farm_animals',
      ),
    ),
  );
  return $actions;
}

/**
 * Implements hook_farm_area_links().
 */
function farm_livestock_farm_area_links($id) {
  return array(
    array(
      'title' => t('Animals'),
      'href' => 'farm/area/' . $id . '/animals',
    ),
  );
}