<?php
/**
 * @file
 * Code for the Farm Maps feature.
 */

include_once 'farm_map.features.inc';

/**
 * Implements hook_openlayers_map_alter().
 */
function farm_map_openlayers_map_alter(&$map = array()) {

  // If this is the Farm Geofield Map, add the Geofield behavior as a zoom-to layer.
  if (!empty($map['map_name']) && $map['map_name'] == 'farm_map_geofield') {
    $map['behaviors']['openlayers_behavior_zoomtolayer']['zoomtolayer']['openlayers_behavior_geofield'] = 'openlayers_behavior_geofield';
  }
}
