<?php
/**
 * @file
 * Code for the Farm Equipment feature.
 */

include_once 'farm_equipment.features.inc';

/**
 * Implements hook_farm_access_perms().
 */
function farm_equipment_farm_access_perms($role) {

  // Assemble a list of entity types provided by this module.
  $types = array(
    'farm_asset' => array(
      'equipment',
    ),
    'log' => array(
      'farm_maintenance',
    ),
  );

  // Grant different CRUD permissions based on the role.
  $perms = array();
  switch ($role) {

    // Farm Manager and Worker
    case 'Farm Manager':
    case 'Farm Worker':
      $perms = farm_access_entity_perms($types);
      break;

    // Farm Viewer
    case 'Farm Viewer':
      $perms = farm_access_entity_perms($types, array('view'));
      break;
  }

  return $perms;
}

/**
 * Implements hook_farm_admin_actions().
 */
function farm_equipment_farm_admin_actions() {

  // Define farm equipment actions.
  $actions = array(
    'equipment' => array(
      'title' => t('Add equipment'),
      'href' => 'farm/asset/add/equipment',
      'views' => array(
        'farm_equipment',
      ),
    ),
    'maintenance' => array(
      'title' => t('Add maintenance'),
      'href' => 'log/add/farm_maintenance',
      'assets' => array(
        'equipment',
      ),
      'views' => array(
        'farm_log_maintenance',
      ),
    ),
  );
  return $actions;
}

/**
 * Implements hook_farm_asset_breadcrumb().
 */
function farm_equipment_farm_asset_breadcrumb($farm_asset) {

  // If the asset is equipment, add a link to the equipment list.
  $breadcrumb = array();
  if ($farm_asset->type == 'equipment') {
    $breadcrumb[] = l(t('Assets'), 'farm/assets');
    $breadcrumb[] = l(t('Equipment'), 'farm/assets/equipment');
  }
  return $breadcrumb;
}

/**
 * Implements hook_farm_asset_view_views().
 */
function farm_equipment_farm_asset_view_views($farm_asset) {

  // If the entity is not equipment, bail.
  if ($farm_asset->type != 'equipment') {
    return array();
  }

  // Return a list of Views to include on Equipment.
  return array(
    array(
      'name' => 'farm_log_activity',
      'weight' => 0,
    ),
    array(
      'name' => 'farm_log_observation',
      'weight' => 10,
    ),
    array(
      'name' => 'farm_log_maintenance',
      'weight' => 20,
    ),
    array(
      'name' => 'farm_log_input',
      'weight' => 50,
    ),
    array(
      'name' => 'farm_log_movement',
      'weight' => 100,
    ),
  );
}

/**
 * Implements hook_farm_taxonomy_term_view_views().
 */
function farm_equipment_farm_taxonomy_term_view_views($term) {

  // If the term is not an area, bail.
  if ($term->vocabulary_machine_name != 'farm_areas') {
    return array();
  }

  // Return a list of Views to include on Areas.
  return array(
    array(
      'name' => 'farm_equipment',
      'weight' => -10,
    ),
  );
}

/**
 * Implements hook_farm_area_links().
 */
function farm_equipment_farm_area_links($id) {
  $links = array();

  // Add link to equipment.
  $view = views_get_view('farm_equipment');
  $view->preview('default', array($id));
  if ($view->total_rows > 0) {
    $links[] = array(
      'title' => t('Equipment') . ': ' . $view->total_rows,
      'href' => 'farm/assets/equipment/' . $id,
    );
  }

  return $links;
}

/**
 * Implements hook_views_post_render().
 */
function farm_equipment_views_post_render(&$view, &$output, &$cache) {

  // If this is the Farm Equipment page...
  if ($view->name == 'farm_equipment' && $view->current_display == 'page') {

    // If there are any arguments, bail.
    /**
     * @todo
     * Display a map that is filtered by the same arguments.
     */
    if (!empty($view->args)) {
      return;
    }

    // If the View result is not empty...
    if (!empty($view->result)) {

      // Add the Equipment asset map to the top of the View.
      $map = \Drupal\openlayers\Openlayers::load('Map', 'farm_assets_equipment');
      $map_build = $map->build();
      $output = drupal_render($map_build) . $output;
    }
  }
}
