<?php
/**
 * @file
 * Code for the Farm MapKnitter module.
 */

/**
 * Implements hook_permission().
 */
function farm_mapknitter_permission() {
  $perms = array(
    'administer farm_mapknitter module' => array(
      'title' => t('Administer farm MapKnitter module'),
    ),
  );
  return $perms;
}

/**
 * Implements hook_farm_manager_perms().
 */
function farm_mapknitter_farm_manager_perms() {

  // Give farm managers access to the mapknitter config.
  return array('administer farm_mapknitter module');
}
