<?php

/**
 * @file
 * The farmOS Flags module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function farm_flag_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  // Add flag field to assets and logs.
  if (in_array($entity_type->id(), ['asset', 'log'])) {

    // Include helper functions.
    module_load_include('inc', 'farm_field', 'farm_field.base_fields');

    // Build field options.
    $options = [
      'type' => 'list_string',
      'label' => t('Flags'),
      'multiple' => TRUE,
      'weight' => [
        'form' => -75,
        'view' => -75,
      ],
    ];
    switch ($entity_type->id()) {

      case 'asset':
        $options['description'] = t('Add flags to this asset to enable better sorting and filtering of records.');
        break;

      case 'log':
        $options['description'] = t('Add flags to this log to enable better sorting and filtering of records.');
        break;

    }
    $options['allowed_values_function'] = 'farm_flag_field_allowed_values';
    $fields['flag'] = farm_field_base_field_definition($options);
  }

  return $fields;
}

/**
 * Implements hook_views_data_alter().
 */
function farm_flag_views_data_alter(array &$data) {

  // Because Drupal core does not provide full Views integration for base fields
  // we must manually specify the list_field views filter for the flag field.
  // Define the views filter settings.
  $flag_filter = [
    'id' => 'list_field',
    'field_name' => 'flag',
    'allow_empty' => TRUE,
  ];

  // Add the filter settings to all flag fields.
  // @todo Add filter for the plan entity flag field.
  $data['log__flag']['flag_value']['filter'] = $flag_filter;
  $data['log_revision_flag']['flag_value']['filter'] = $flag_filter;
  $data['asset__flag']['flag_value']['filter'] = $flag_filter;
  $data['asset_revision_flag']['flag_value']['filter'] = $flag_filter;
}

/**
 * Allowed values callback function for the flags field.
 *
 * @return array
 *   Returns an array of allowed values for use in form select options.
 */
function farm_flag_field_allowed_values() {
  /** @var \Drupal\farm_flag\Entity\FarmFlagInterface[] $flags */
  $flags = \Drupal::entityTypeManager()->getStorage('flag')->loadMultiple();
  $allowed_values = [];
  foreach ($flags as $id => $flag) {
    $allowed_values[$id] = $flag->getLabel();
  }
  return $allowed_values;
}
