<?php

/**
 * @file
 * The farmOS Flags module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function farm_flag_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  // Add flag field to assets, logs, and plans.
  if (in_array($entity_type->id(), ['asset', 'log', 'plan'])) {

    // Include helper functions.
    module_load_include('inc', 'farm_field', 'farm_field.base_fields');

    // Build field options.
    $options = [
      'type' => 'list_string',
      'label' => t('Flags'),
      'description' => t('Add flags to enable better sorting and filtering of records.'),
      'multiple' => TRUE,
      'weight' => [
        'form' => -75,
        'view' => -75,
      ],
      'allowed_values_function' => 'farm_flag_field_allowed_values',
    ];
    $fields['flag'] = \Drupal::service('farm_field.factory')->baseFieldDefinition($options);
  }

  return $fields;
}

/**
 * Implements hook_views_data_alter().
 */
function farm_flag_views_data_alter(array &$data) {

  // Because Drupal core does not provide full Views integration for base fields
  // we must manually specify the list_field views filter for the flag field.
  // Define the views filter settings.
  $flag_filter = [
    'id' => 'list_field',
    'field_name' => 'flag',
    'allow_empty' => TRUE,
  ];
  $tables = [
    'asset__flag',
    'asset_revision__flag',
    'log__flag',
    'log_revision__flag',
    'plan__flag',
    'plan_revision__flag',
  ];
  foreach ($tables as $table) {
    if (!empty($data[$table]['flag_value'])) {
      $data[$table]['flag_value']['filter'] = $flag_filter;
    }
  }
}

/**
 * Allowed values callback function for the flags field.
 *
 * @return array
 *   Returns an array of allowed values for use in form select options.
 */
function farm_flag_field_allowed_values() {
  /** @var \Drupal\farm_flag\Entity\FarmFlagInterface[] $flags */
  $flags = \Drupal::entityTypeManager()->getStorage('flag')->loadMultiple();
  $allowed_values = [];
  foreach ($flags as $id => $flag) {
    $allowed_values[$id] = $flag->getLabel();
  }
  return $allowed_values;
}
