<?php

/**
 * @file
 * Hooks and customizations for the plan module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function plan_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  // Main module help for the plan module.
  if ($route_name == 'help.page.plan') {
    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Provides plan entity') . '</p>';
  }

  return $output;
}
