<?php
/**
 * @file
 * Code for the Farm Soil Test feature.
 */

include_once 'farm_soil_test.features.inc';

/**
 * Implements hook_menu_local_tasks_alter().
 */
function farm_soil_test_menu_local_tasks_alter(&$data, $router_item, $root_path) {

  // Define actions.
  $actions = array(
    'soil_test' => array(
      'title' => t('Add a soil test'),
      'href' => 'log/add/farm_soil_test',
    ),
  );

  // Define actions for various paths.
  $path_actions = array(
    'farm/area/%/soil-tests' => array('soil_test'),
    'admin/farm/areas/soil-tests' => array('soil_test'),
  );

  // Add actions depending on the root path.
  if (array_key_exists($root_path, $path_actions)) {
    foreach ($path_actions[$root_path] as $action) {
      $output = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => $actions[$action]['title'],
          'href' => $actions[$action]['href'],
          'localized_options' => array(
            'query' => array(
              'destination' => $root_path,
            ),
          ),
        ),
      );

      // Or, if this is a farm area path...
      if ($root_path == 'taxonomy/term/%' || substr($root_path, 0, 11) == 'farm/area/%') {

        // Get the area id from the path.
        $area_id = check_plain(arg(2));

        // Load the area.
        $farm_area = taxonomy_term_load($area_id);

        // If the taxonomy term is not a farm_area, bail.
        if (empty($farm_area->vocabulary_machine_name) || $farm_area->vocabulary_machine_name != 'farm_areas') {
          continue;
        }

        // Set the destination to the farm asset page.
        $output['#link']['localized_options']['query']['destination'] = 'taxonomy/term/' . $area_id;

        // Set the farm_area query string to the area id. This will be used to
        // prepopulate area(s) reference fields in log entities.
        // See hook_form_alter() below
        $output['#link']['localized_options']['query']['farm_area'] = $area_id;
      }

      // Add the action output.
      $data['actions']['output'][] = $output;
    }
  }
}

/**
 * Implements hook_farm_area_links().
 */
function farm_soil_test_farm_area_links($id) {
  return array(
    array(
      'title' => t('Soil Tests'),
      'href' => 'farm/area/' . $id . '/soil_tests',
      'weight' => 100,
    ),
  );
}