<?php
/**
 * @file
 * Code for the Farm Log: Activity feature.
 */

// Include Features code.
include_once 'farm_log_activity.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_log_activity_farm_ui_entities() {
  return array(
    'log' => array(
      'farm_activity' => array(
        'label' => t('Activity'),
        'label_plural' => t('Activities'),
        'view' => 'farm_log_activity',
        'areas' => TRUE,
        'weight' => -10,
      ),
    ),
  );
}

/**
 * Implements hook_farm_ui_taxonomy_views().
 */
function farm_log_activity_farm_ui_taxonomy_views($term) {

  // If the term is not an area, bail.
  if ($term->vocabulary_machine_name != 'farm_areas') {
    return array();
  }

  // Return a list of Views to include on Areas.
  return array(
    array(
      'name' => 'farm_log_activity',
      'arg' => 2,
    ),
  );
}
