<?php

/**
 * @file
 * Contains farm_log_query_test.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_base_field_info().
 */
function farm_log_query_test_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  // We add an asset reference field to logs manually here so that tests don't
  // need to depend on farm_entity_fields, which adds a lot more.
  if ($entity_type->id() == 'log') {
    $options = [
      'type' => 'entity_reference',
      'label' => t('Asset'),
      'target_type' => 'asset',
      'multiple' => TRUE,
    ];
    $fields['asset'] = \Drupal::service('farm_field.factory')->baseFieldDefinition($options);
  }

  return $fields;
}
