# Schema for the configuration files of the plan module.
plan.type.*:
  type: config_entity
  label: 'Plan type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Type'
    description:
      type: text
      label: 'Description'
    workflow:
      type: string
      label: 'Workflow'
    new_revision:
      type: boolean
      label: 'Create new revision'

plan.record.type.*:
  type: config_entity
  label: 'Plan record relationship type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Type'
    description:
      type: text
      label: 'Description'

condition.plugin.plan_type:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string

action.configuration.plan_activate_action:
  type: action_configuration_default
  label: 'Configuration for the plan activate action'

action.configuration.plan_archive_action:
  type: action_configuration_default
  label: 'Configuration for the plan archive action'
