<?php
/**
 * @file
 * Code for the Farm Soil: Compost feature.
 */

include_once 'farm_soil_compost.features.inc';

/**
 * Implements hook_farm_ui_actions().
 */
function farm_soil_compost_farm_ui_actions() {

  // Define farm compost actions.
  $actions = array(
    'compost' => array(
      'title' => t('Add compost'),
      'href' => 'farm/asset/add/compost',
      'views' => array(
        'farm_compost',
      ),
    ),
  );
  return $actions;
}

/**
 * Implements hook_farm_area_links().
 */
function farm_soil_compost_farm_area_links($id) {
  $links = array();

  // Add link to compost.
  $view = views_get_view('farm_compost');
  $view->preview('default', array($id));
  if ($view->total_rows > 0) {
    $links[] = array(
      'title' => t('Compost') . ': ' . $view->total_rows,
      'href' => 'farm/assets/compost/' . $id,
    );
  }

  return $links;
}

/**
 * Implements hook_farm_ui_asset_breadcrumb().
 */
function farm_soil_compost_farm_ui_asset_breadcrumb($farm_asset) {

  // If the asset is a compost, add a link to the compost list.
  $breadcrumb = array();
  if ($farm_asset->type == 'compost') {
    $breadcrumb[] = l(t('Assets'), 'farm/assets');
    $breadcrumb[] = l(t('Compost'), 'farm/assets/compost');
  }
  return $breadcrumb;
}

/**
 * Implements hook_farm_asset_view_views().
 */
function farm_soil_compost_farm_asset_view_views($farm_asset) {

  // If the entity is not a compost bail.
  if ($farm_asset->type != 'compost') {
    return array();
  }

  // Return a list of Views to include on Compost assets.
  return array(
    array(
      'name' => 'farm_log_activity',
      'weight' => 0,
    ),
    array(
      'name' => 'farm_log_observation',
      'weight' => 10,
    ),
    array(
      'name' => 'farm_log_input',
      'weight' => 50,
    ),
    array(
      'name' => 'farm_log_harvest',
      'weight' => 60,
    ),
    array(
      'name' => 'farm_log_movement',
      'weight' => 100,
    ),
    array(
      'name' => 'farm_asset_children',
      'display' => 'page',
      'title' => t('Children'),
      'weight' => 110,
    ),
  );
}

/**
 * Implements hook_farm_taxonomy_term_view_views().
 */
function farm_soil_compost_farm_taxonomy_term_view_views($term) {

  // If the term is not an area, bail.
  if ($term->vocabulary_machine_name != 'farm_areas') {
    return array();
  }

  // Return a list of Views to include on Areas.
  return array(
    array(
      'name' => 'farm_compost',
    ),
  );
}

/**
 * Implements hook_views_post_render().
 */
function farm_soil_compost_views_post_render(&$view, &$output, &$cache) {

  // If this is the Farm Compost page...
  if ($view->name == 'farm_compost' && $view->current_display == 'page') {

    // If dashboard maps are disabled in the farm_map module settings, bail.
    if (!variable_get('farm_map_show', TRUE)) {
      return;
    }

    // If there are any arguments, bail.
    /**
     * @todo
     * Display a map that is filtered by the same arguments.
     */
    if (!empty($view->args)) {
      return;
    }

    // If the View result is not empty...
    if (!empty($view->result)) {

      // Add the Compost asset map to the top of the View.
      $map = \Drupal\openlayers\Openlayers::load('Map', 'farm_assets_compost');
      if (!empty($map)) {
        $map_build = $map->build();
        $output = drupal_render($map_build) . $output;
      }
    }
  }
}

/**
 * Implements hook_farm_log_categories().
 */
function farm_soil_compost_farm_log_categories() {

  // Provide an "Compost" log category.
  return array('Compost');
}
