<?php

/**
 * @file
 * Hooks and customizations for the farm_l10n module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function farm_l10n_form_language_admin_overview_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Disable the ability to change the site's default language and direct users
  // to /farm/settings/language instead.
  // @see https://www.drupal.org/project/farm/issues/3257430
  $message = t('To change the default language of farmOS, please go to <a href=":url">farmOS language settings</a>.', [':url' => Url::fromRoute('farm_l10n.settings')->toString()]);
  \Drupal::messenger()->addWarning($message);
  foreach (Element::children($form['languages']) as $langcode) {
    $form['languages'][$langcode]['default']['#access'] = FALSE;
  }
}
