# Inherits from docker-compose.testing.common.yml
version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - './db:/var/lib/mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: farm
      MYSQL_DATABASE: farm
      MYSQL_USER: farm
      MYSQL_PASSWORD: farm

  www:
    depends_on:
      - db

  test-runner:
    command:
      - -c
      - |
        set -e
        # Wait until the dev farmOS container has finished copying its files
        until [ -f /opt/drupal/www-container-fs-ready ]; do sleep 0.1; done
        # Wait until mariadb is online listening to its socket
        while { ! exec 3<>/dev/tcp/db/3306; } > /dev/null 2>&1; do sleep 0.1; done
        # Run normal entrypoint and apache - only at this point is the test-runner-container-fs-ready
        # file created, allowing the Github action to also wait for the above conditions on the basis
        # of that file's creation.
        exec docker-entrypoint.sh apache2-foreground
