<?php

/**
 * @file
 * Contains farm_log.module.
 */

use Drupal\farm_log\Event\LogEvent;
use Drupal\log\Entity\LogInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function farm_log_log_presave(LogInterface $log) {

  // Dispatch an event on log presave.
  // @todo Replace this with core event via https://www.drupal.org/node/2551893.
  $event = new LogEvent($log);
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch(LogEvent::PRESAVE, $event);
}
