asset_map_popup:
  css:
    theme:
      css/asset_map_popup.css: { }
content_form:
  css:
    theme:
      css/content-form.css: { }
dashboard:
  css:
    theme:
      css/dashboard.css: { }
flag:
  css:
    theme:
      css/flag.css: { }
footer:
  css:
    theme:
      css/footer.css: { }
help:
  css:
    theme:
      css/help.css: { }
layout:
  css:
    theme:
      css/layout.css: { }
map:
  css:
    theme:
      css/map.css: { }
  dependencies:
    - farm_map/farm_map
menu_local_task:
  css:
    theme:
      css/menu-local-task.css: { }
quick:
  css:
    theme:
      css/quick.css: { }
regions:
  css:
    theme:
      css/regions.css: { }
toolbar:
  css:
    theme:
      css/toolbar.css: { }
  js:
    js/toolbar.js: { weight: -50 }
views:
  css:
    theme:
      css/views.css: { }
