<?php

/**
 * @file
 * Farm Client module.
 */

/**
 * Implements hook_farm_api_oauth2_client().
 */
function farm_client_farm_api_oauth2_client() {
  $clients = array();

  $clients['farm_client'] = array(
    'label' => 'farmOS Client (Field Kit)',
    'client_key' => 'farm_client',
    'redirect_uri' => '',
  );

  return $clients;
}

/**
 * Implements hook_farm_info().
 */
function farm_client_farm_info() {

  // Ask modules for client module info.
  $client_modules = module_invoke_all('farm_client_modules');

  // Add the client module info to /farm.json.
  $info = array();
  if (!empty($client_modules)) {
    $info['client'] = array(
      'modules' => $client_modules,
    );
  }
  return $info;
}
