<?php

/**
 * @file
 * Farm equipment field module.
 */

/**
 * Implements hook_farm_fields_dynamic_bases().
 */
function farm_equipment_farm_fields_dynamic_bases() {
  return array(
    'field_farm_equipment' => array(
      'active' => 1,
      'cardinality' => -1,
      'deleted' => 0,
      'entity_types' => array(),
      'field_name' => 'field_farm_equipment',
      'indexes' => array(
        'target_id' => array(
          0 => 'target_id',
        ),
      ),
      'locked' => 0,
      'module' => 'entityreference',
      'settings' => array(
        'handler' => 'base',
        'handler_settings' => array(
          'behaviors' => array(
            'views-select-list' => array(
              'status' => 0,
            ),
          ),
          'sort' => array(
            'type' => 'none',
          ),
          'target_bundles' => array(
            0 => 'equipment',
          ),
        ),
        'target_type' => 'farm_asset',
      ),
      'translatable' => 0,
      'type' => 'entityreference',
    ),
  );
}

/**
 * Implements hook_farm_fields_dynamic_instances().
 */
function farm_equipment_farm_fields_dynamic_instances() {

  // Start an empty array of field instance definitions.
  $field_instances = array();

  // Get a list of log types.
  $log_types = log_types();

  // Iterate through the log types and add an equipment reference field to each.
  foreach ($log_types as $bundle => $info) {
    $field_instances['log-' . $bundle . '-field_farm_equipment'] = array(
      'bundle' => $bundle,
      'deleted' => 0,
      'description' => 'What equipment was used?',
      'display' => array(
        'default' => array(
          'label' => 'inline',
          'module' => 'entityreference',
          'settings' => array(
            'bypass_access' => FALSE,
            'link' => 1,
          ),
          'type' => 'entityreference_label',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'log',
      'field_name' => 'field_farm_equipment',
      'label' => t('Equipment used'),
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'entityreference_view_widget',
        'settings' => array(
          'allow_duplicates' => 0,
          'close_modal' => 1,
          'pass_argument' => 1,
          'pass_arguments' => '',
          'rendered_entity' => 0,
          'view' => 'farm_asset_entityreference_view|entityreference_view_widget',
          'view_mode' => 'full',
        ),
        'type' => 'entityreference_view_widget',
        'weight' => 2,
      ),
    );
  }

  // Return the array of field instance definitions.
  return $field_instances;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function farm_equipment_field_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_field_group_info_alter().
 */
function farm_equipment_field_field_group_info_alter(&$groups) {

  // Iterate through the groups and make a list of asset and general groups.
  $asset_groups = array();
  $general_groups = array();
  foreach ($groups as $key => $group) {

    // If we don't know the entity type, bail.
    if (empty($group->entity_type)) {
      continue;
    }

    // Only alter logs.
    if ($group->entity_type != 'log') {
      continue;
    }

    // Only alter the form.
    if ($group->mode != 'form') {
      continue;
    }

    // Add it to one of the listed based on its name.
    switch ($group->group_name) {
      case 'group_farm_assets':
        $asset_groups[] = $key;
        break;
      case 'group_farm_general':
        $general_groups[] = $key;
        break;
    }
  }

  // Remove general groups on log types that have an assets group.
  foreach ($asset_groups as $key) {

    // Get the asset group from the original groups array.
    $asset_group = $groups[$key];

    // Assemble the identifier for this bundle's general group.
    $parts = array(
      'group_farm_general',
      $asset_group->entity_type,
      $asset_group->bundle,
      $asset_group->mode,
    );
    $general_group_key = implode('|', $parts);

    // Remove the general group.
    $key = array_search($general_group_key, $general_groups);
    if ($key !== FALSE) {
      unset($general_groups[$key]);
    }
  }

  // Merge the asset and general groups into a final list of groups we want to
  // add the equipment field to.
  $alter_groups = array_merge($asset_groups, $general_groups);

  // Iterate through the groups we want to alter.
  foreach ($alter_groups as $key) {

    // Add the "Equipment used" field.
    $groups[$key]->data['children'][] = "field_farm_equipment";
  }
}
