<?php
/**
 * @file
 * Code for the Farm Livestock: Eggs feature.
 */

include_once 'farm_livestock_eggs.features.inc';

/**
 * Implements hook_menu_local_tasks_alter().
 */
function farm_livestock_eggs_menu_local_tasks_alter(&$data, $router_item, $root_path) {

  // Define actions.
  $actions = array(
    'eggs' => array(
      'title' => t('Add eggs'),
      'href' => 'log/add/farm_eggs',
    ),
  );

  // Define actions for various paths.
  $path_actions = array(
    'admin/farm/livestock/eggs' => array('eggs'),
  );

  // Add actions depending on the root path.
  if (array_key_exists($root_path, $path_actions)) {
    foreach ($path_actions[$root_path] as $action) {
      $output = array(
        '#theme' => 'menu_local_action',
        '#link' => array(
          'title' => $actions[$action]['title'],
          'href' => $actions[$action]['href'],
          'localized_options' => array(
            'query' => array(
              'destination' => $root_path,
            ),
          ),
        ),
      );

      // Add the action output.
      $data['actions']['output'][] = $output;
    }
  }
}
