<?php
/**
 * @file
 * Code for the Farm Livestock: Eggs feature.
 */

include_once 'farm_livestock_eggs.features.inc';

/**
 * Implements hook_farm_admin_actions().
 */
function farm_livestock_eggs_farm_admin_actions() {

  // Define farm area actions.
  $actions = array(
    'eggs' => array(
      'title' => t('Add eggs'),
      'href' => 'log/add/farm_eggs',
      'views' => array(
        'farm_animals',
        'farm_log_eggs',
      ),
    ),
  );
  return $actions;
}
