<?php

/**
 * @file
 * Install, update and uninstall functions for the farm_api module.
 */

declare(strict_types=1);

/**
 * Implements hook_install().
 */
function farm_api_install() {

  // Allow JSON:API write operations.
  \Drupal::configFactory()->getEditable('jsonapi.settings')->set('read_only', FALSE)->save();
}

/**
 * Implements hook_update_last_removed().
 */
function farm_api_update_last_removed() {
  return 9001;
}
