<?php

/**
 * @file
 * Contains farm_api.module.
 */

declare(strict_types=1);

/**
 * Implements hook_farm_api_allow_resource_types().
 */
function farm_api_farm_api_allow_resource_types() {

  // Allow farmOS core entity types on behalf of the modules that provide them.
  return [
    'asset',
    'asset_type',
    'data_stream',
    'data_stream_type',
    'file',
    'log',
    'log_type',
    'plan',
    'plan_type',
    'plan_record',
    'plan_record_type',
    'quantity',
    'quantity_type',
    'taxonomy_term',
    'taxonomy_vocabulary',
    'user',
    'user_role',
  ];
}
