<?php

/**
 * @file
 * Land asset module.
 */

/**
 * Allowed values callback function for the land type field.
 *
 * @return array
 *   Returns an array of allowed values for use in form select options.
 */
function farm_land_type_field_allowed_values() {
  /** @var \Drupal\farm_land\Entity\FarmLandTypeInterface[] $types */
  $types = \Drupal::entityTypeManager()->getStorage('land_type')->loadMultiple();
  $allowed_values = [];
  foreach ($types as $id => $type) {
    $allowed_values[$id] = $type->getLabel();
  }
  return $allowed_values;
}
