<?php
/**
 * @file
 * Code for the Farm Equipment feature.
 */

include_once 'farm_equipment.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_equipment_farm_ui_entities() {
  return array(
    'farm_asset' => array(
      'equipment' => array(
        'label' => t('Equipment'),
        'label_plural' => t('Equipment'),
        'view' => 'farm_equipment',
      ),
    ),
    'log' => array(
      'farm_maintenance' => array(
        'label' => t('Maintenance'),
        'label_plural' => t('Maintenance'),
        'view' => 'farm_log_maintenance',
        'farm_asset' => 'equipment',
        'weight' => 20,
      ),
    ),
  );
}

/**
 * Implements hook_farm_log_categories().
 */
function farm_equipment_farm_log_categories() {

  // Provide an "Equipment" log category.
  return array('Equipment');
}
