<?php

/**
 * @file
 * The farmOS UI Map module.
 */

/**
 * Implements hook_theme().
 */
function farm_ui_map_theme($existing, $type, $theme, $path) {
  return [
    'html__asset__map_popup' => [
      'base hook' => 'html',
    ],
  ];
}

/**
 * Implements hook_farm_dashboard_panes().
 */
function farm_ui_map_farm_dashboard_panes() {
  return [
    'dashboard_map' => [
      'block' => 'dashboard_map',
      'region'  => 'top',
    ],
  ];
}

/**
 * Implements hook_module_implements_alter().
 */
function farm_ui_map_module_implements_alter(&$implementations, $hook) {

  // Ensure that this module's hook_views_pre_render() runs first.
  if ($hook == 'views_pre_render') {
    $module = 'farm_ui_map';
    $group = $implementations[$module];
    unset($implementations[$module]);
    $implementations = array_merge([$module => $group], $implementations);
  }
}
