<?php

/**
 * @file
 * Quantity module.
 */

/**
 * Define information about available quantity measures.
 *
 * @return array
 *   Returns an array of measure information.
 */
function quantity_measures() {
  return [
    'count' => [
      'label' => t('Count'),
    ],
    'length' => [
      'label' => t('Length/depth'),
    ],
    'weight' => [
      'label' => t('Weight'),
    ],
    'area' => [
      'label' => t('Area'),
    ],
    'volume' => [
      'label' => t('Volume'),
    ],
    'time' => [
      'label' => t('Time'),
    ],
    'temperature' => [
      'label' => t('Temperature'),
    ],
    'pressure' => [
      'label' => t('Pressure'),
    ],
    'water_content' => [
      'label' => t('Water content'),
    ],
    'value' => [
      'label' => t('Value'),
    ],
    'rate' => [
      'label' => t('Rate'),
    ],
    'rating' => [
      'label' => t('Rating'),
    ],
    'ratio' => [
      'label' => t('Ratio'),
    ],
    'probability' => [
      'label' => t('Probability'),
    ],
  ];
}

/**
 * Define available options for the Measure field.
 */
function quantity_measure_options() {

  // Start an empty options array.
  $options = [];

  // Load information about measures.
  $measures = quantity_measures();

  // Iterate through the measures and build a list of options.
  foreach ($measures as $measure => $data) {
    $options[$measure] = $data['label'];
  }

  // Return the array of options.
  return $options;
}

/**
 * Implements hook_farm_api_meta_alter().
 */
function quantity_farm_api_meta_alter(&$data) {

  // Add the quantity system of measurement.
  $data['system_of_measurement'] = \Drupal::config('quantity.settings')->get('system_of_measurement');
}

/**
 * Implements hook_theme().
 */
function quantity_theme() {
  return [
    'quantity' => [
      'render element' => 'elements',
    ],
    'field__quantity__quantity' => [
      'template' => 'field--quantity--quantity',
      'base hook' => 'field',
    ],
  ];
}
