<?php
/**
 * @file
 * Code for the Farm Log: Observation feature.
 */

// Include Features code.
include_once 'farm_log_observation.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_log_observation_farm_ui_entities() {
  return array(
    'log' => array(
      'farm_observation' => array(
        'label' => t('Observation'),
        'label_plural' => t('Observations'),
        'view' => 'farm_log_observation',
        'areas' => TRUE,
        'weight' => -10,
      ),
    ),
  );
}

/**
 * Implements hook_farm_ui_entity_views().
 */
function farm_log_observation_farm_ui_entity_views($entity_type, $bundle, $entity) {
  $views = array();

  // Return a list of Views to include on Areas.
  if ($entity_type == 'taxonomy_term' && $entity->vocabulary_machine_name == 'farm_areas') {
    $views[] = array(
      'name' => 'farm_log_observation',
      'arg' => 2,
    );
  }

  return $views;
}
