<?php
/**
 * @file
 * Code for the Farm Log: Observation feature.
 */

// Include Features code.
include_once 'farm_log_observation.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_log_observation_farm_ui_entities() {
  return array(
    'log' => array(
      'farm_observation' => array(
        'label' => t('Observation'),
        'label_plural' => t('Observations'),
        'view' => 'farm_log_observation',
        'areas' => TRUE,
      ),
    ),
  );
}

/**
 * Implements hook_farm_taxonomy_term_view_views().
 */
function farm_log_observation_farm_taxonomy_term_view_views($term) {

  // If the term is not an area, bail.
  if ($term->vocabulary_machine_name != 'farm_areas') {
    return array();
  }

  // Return a list of Views to include on Areas.
  return array(

    // Observations in this area.
    array(
      'name' => 'farm_log_observation',
      'arg' => 2,
    ),
  );
}
