<?php
/**
 * @file
 * Code for the Farm Soil feature.
 */

include_once 'farm_soil.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_soil_farm_ui_entities() {
  return array(
    'taxonomy_term' => array(
      'farm_soil_names' => array(
        'label' => t('Soil name'),
        'label_plural' => t('Soil names'),
      ),
    ),
  );
}

/**
 * Implements hook_farm_log_categories().
 */
function farm_soil_farm_log_categories() {

  // Provide log categories: Soil, Tillage.
  return array('Soil', 'Tillage');
}
