name: farm_settings (deprecated)
description: This module has merged into the farm_setup module.
type: module
package: farmOS (deprecated)
core_version_requirement: ^10
lifecycle: obsolete
lifecycle_link: 'https://www.drupal.org/node/3559903'
