<?php

/**
 * @file
 * Hooks and customizations for the farm_update module.
 */

/**
 * Implements hook_rebuild().
 */
function farm_update_rebuild() {
  \Drupal::service('farm.update')->rebuild();
}

/**
 * Implements hook_farm_update_exclude_config().
 */
function farm_update_farm_update_exclude_config() {

  // Exclude Drupal core configurations from automatic updates.
  return [
    'user.role.anonymous',
    'user.role.authenticated',
  ];
}
