<?php
/**
 * @file
 * Code for the Farm Log: Harvest feature.
 */

// Include Features code.
include_once 'farm_log_harvest.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_log_harvest_farm_ui_entities() {
  return array(
    'log' => array(
      'farm_harvest' => array(
        'label' => t('Harvest'),
        'label_plural' => t('Harvests'),
        'view' => 'farm_log_harvest',
        'weight' => 80,
      ),
    ),
  );
}
