<?php
/**
 * @file
 * Code for the Farm Log: Harvest feature.
 */

// Include Features code.
include_once 'farm_log_harvest.features.inc';

/**
 * Implements hook_farm_access_perms().
 */
function farm_log_harvest_farm_access_perms($role) {

  // Assemble a list of log types provided by this module.
  $types = array(
    'log' => array(
      'farm_harvest',
    ),
  );

  // Grant different CRUD permissions based on the role.
  $perms = array();
  switch ($role) {

    // Farm Manager and Worker
    case 'Farm Manager':
    case 'Farm Worker':
      $perms = farm_access_entity_perms($types);
      break;

    // Farm Viewer
    case 'Farm Viewer':
      $perms = farm_access_entity_perms($types, array('view'));
      break;
  }

  return $perms;
}

/**
 * Implements hook_farm_admin_actions().
 */
function farm_log_harvest_farm_admin_actions() {

  // Define farm area actions.
  $actions = array(
    'harvest' => array(
      'title' => t('Add a harvest'),
      'href' => 'log/add/farm_harvest',
      'assets' => array(
        'all',
      ),
      'views' => array(
        'farm_log_harvest',
      ),
    ),
  );
  return $actions;
}
