<?php

/**
 * @file
 * The farmOS UI Views module.
 */

/**
 * Implements hook_farm_dashboard_panes().
 */
function farm_ui_views_farm_dashboard_panes() {
  return [
    'upcoming_tasks' => [
      'view' => 'farm_log',
      'view_display_id' => 'block_upcoming',
      'group' => 'logs',
      'weight' => 10,
    ],
    'late_tasks' => [
      'view' => 'farm_log',
      'view_display_id' => 'block_late',
      'group' => 'logs',
      'weight' => 11,
    ],
  ];
}
