<?php

/**
 * @file
 * Install, update and uninstall function for the farm_image module.
 */

declare(strict_types=1);

use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_install().
 */
function farm_image_install() {

  // If the imagick PHP extension is available...
  if (extension_loaded('imagick')) {

    // Install the imagick module.
    if (!\Drupal::service('module_handler')->moduleExists('imagick')) {
      \Drupal::service('module_installer')->install(['imagick']);
    }

    // Make imagick the default image toolkit.
    $config = \Drupal::configFactory()->getEditable('system.image');
    $config->set('toolkit', 'imagick');
    $config->save();

    // Configure imagick to disable strip_metadata.
    // This ensures that EXIF data is preserved in derivative images, which
    // allows browsers to auto-orient them if they have Orientation data.
    $config = \Drupal::configFactory()->getEditable('imagick.config');
    $config->set('strip_metadata', FALSE);
    $config->save();
  }

  // Add auto-orient effect to Drupal core image styles.
  $styles = [
    'large',
    'medium',
    'thumbnail',
    'wide',
  ];
  foreach ($styles as $name) {
    $style = ImageStyle::load($name);
    if (!is_null($style)) {
      $style->addImageEffect([
        'id' => 'farm_image_auto_orient',
        'weight' => -1,
      ]);
      $style->save();
    }
  }
}
