<?php
/**
 * @file
 * Code for the Farm Livestock: Eggs feature.
 */

include_once 'farm_livestock_eggs.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_livestock_eggs_farm_ui_entities() {
  return array(
    'log' => array(
      'farm_eggs' => array(
        'label' => t('Egg log'),
        'label_plural' => t('Egg logs'),
        'view' => 'farm_log_eggs',
      ),
    ),
  );
}
