<?php
/**
 * @file
 * Code for the Farm Livestock: Eggs feature.
 */

include_once 'farm_livestock_eggs.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_livestock_eggs_farm_ui_entities() {
  return array(
    'log' => array(
      'farm_eggs' => array(
        'label' => t('Egg log'),
        'label_plural' => t('Egg logs'),
        'view' => 'farm_log_eggs',
        'farm_asset' => 'none',
      ),
    ),
  );
}

/**
 * Implements hook_feeds_importer_default_alter().
 */
function farm_livestock_eggs_feeds_importer_default_alter(&$importers) {

  // Add extra field mappings to eggs.
  $name = 'log_farm_eggs';
  if (!empty($importers[$name])) {
    $mappings = array(
      array(
        'source' => 'Quantity',
        'target' => 'field_farm_egg_qty',
        'unique' => FALSE,
        'language' => 'und',
      ),
      array(
        'source' => 'Group',
        'target' => 'field_farm_animal_group',
        'unique' => FALSE,
        'language' => 'und',
      ),
    );
    $importer_mappings =& $importers[$name]->config['processor']['config']['mappings'];
    $importer_mappings = array_merge($importer_mappings, $mappings);
  }
}

/**
 * Implements hook_feeds_tamper_default_alter().
 */
function farm_livestock_eggs_feeds_tamper_default_alter(&$feeds_tampers) {

  // If farm_import is not installed, bail.
  if (!module_exists('farm_import')) {
    return;
  }

  // Explode group so it supports multiple values.
  $feeds_tamper = farm_import_feeds_tamper_plugin('log', 'farm_eggs', 'Group', 'explode');
  $feeds_tampers[$feeds_tamper->id] = $feeds_tamper;
}
