<?php
/**
 * @file
 * Code for the Farm Admin feature.
 */

/**
 * Implements hook_modules_installed().
 */
function farm_admin_modules_installed($modules) {

  // If the menu module is installed, create the farm menu.
  if (in_array('menu', $modules)) {
    farm_admin_menu_save();
  }
}

/**
 * Implements hook_permission().
 */
function farm_admin_permission() {
  return array(
    'access farm dashboard' => array(
      'title' => t('Access farm dashboard'),
      'description' => t('Access the farm dashboard.'),
    ),
  );
}

/**
 * Implements hook_farm_access_perms().
 */
function farm_admin_farm_access_perms($role) {
  $perms = array();

  // Access farm dashboard.
  $perms[] = 'access farm dashboard';

  return $perms;
}

/**
 * Implements hook_menu().
 */
function farm_admin_menu() {

  $items['farm'] = array(
    'title' => 'Farm',
    'page callback' => 'farm_admin_dashboard',
    'access arguments' => array('access farm dashboard'),
    'type' => MENU_CALLBACK,
  );
  $items['farm/dashboard'] = array(
    'title' => 'Farm',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -100,
  );

  // Root farm configuration path.
  $items['admin/config/farm'] = array(
    'title' => 'Farm',
    'description' => 'Configure settings for your farm.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  );

  return $items;
}

/**
 * Farm dashboard page callback.
 */
function farm_admin_dashboard() {

  // Set the page title.
  drupal_set_title('Dashboard');

  // Start an output string.
  $output = '';

  // Display the current date.
  $output .= '<h2>Today is ' . date('M j Y') . '</h2>';

  // Render the "Plan" block display.
  $view = views_get_view('farm_log');
  $preview = $view->preview('block_plan');
  $title = $title = $view->get_title();
  $output .= '<h2 id="' . $title . '">' . $title . '</h3>' . $preview;

  // Render the "Late tasks" block display (only if there are results).
  $view = views_get_view('farm_log');
  $preview = $view->preview('block_late_tasks');
  if (!empty($view->total_rows)) {
    $title = $title = $view->get_title();
    $output .= '<h2 id="' . $title . '">' . $title . '</h3>' . $preview;
  }

  // Return the output.
  return $output;
}

/**
 * Implements hook_menu_breadcrumb_alter().
 */
function farm_admin_menu_breadcrumb_alter(&$active_trail, $item) {

  // If the current path contains /farm...
  if (strpos($item['path'], 'farm') === 0) {

    // If the link to /farm already exists in the second position, bail.
    if (!empty($active_trail[1]['link_path']) && $active_trail[1]['link_path'] == 'farm') {
      return;
    }

    // Add an item for /farm.
    $start = array_shift($active_trail);
    $farm_item = menu_get_item('farm');
    array_unshift($active_trail, $farm_item);
    array_unshift($active_trail, $start);
  }
}

/**
 * Implements hook_navbar().
 */
function farm_admin_navbar() {

  // Farm tab.
  $items['farm'] = array(
    '#type' => 'navbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('Farm'),
      '#href' => 'farm',
      '#options' => array(
        'attributes' => array(
          'title' => t('Farm management'),
          'class' => array('navbar-icon', 'navbar-icon-dashboard'),
        ),
      ),
    ),
    '#weight' => 20,
  );
  return $items;
}

/**
 * Generate the farm menu.
 *
 * @see farm_admin_enable()
 * @see farm_admin_install_modules()
 */
function farm_admin_menu_save() {
  $t = get_t();
  $menu = array(
    'menu_name' => 'farm',
    'title' => $t('Farm'),
    'description' => $t('Farm management links'),
  );
  menu_save($menu);
}
